---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Secret
metadata:
  name: gzip-uploader-tls
  namespace: dev
type: kubernetes.io/tls
data:
  ca.crt: ''
  tls.key: 'LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQ3p2ZGUyanRQeXpvMnMKaW84OENLU3VPczJqT2NhVjUzZXc1TGtBOVNZKzdiUWppY3RiUEpmVVJWLzZYMUlXam14STBhcXJtc2RvdXBGRApIWHoxRWsrTzJJaHVDQ0RUQnhQbWdoUWtlbHBHdGd5RHEyS0IzRXJEU1VoZXNGcGJScmZDZ1lQZzNpR09IS1lBCkE3Q3lUczB3YXZUWTZ6RnNFZUhJSEtYcFdFQ0ZZVEozWDZwbWowZ3ZEbXdUeVZ4SEFLZlA0dk01R3FIdGIwZksKdVlQNSt1ei9EaVhLdUNjdVZhUnJsOEZXUTI3dzJFWGJpVURWZDUyQS9XWnBGRkZyV2dlMHM4SU8rMmx2Z2xPYgp5OWdqZmF2d2ZvL0xKTGE1MHk3MU9hUFd5SjZVNTQyZXRNSEFVaEw3ZEY0Z0s2M0JkaVdlZm5pVHV2bU14dGJyCnVBN1lGNUhUQWdNQkFBRUNnZ0VBYkpjalBlM29hdWNUZk14eFlNbXdCSHNPUmJEZ0l5eW1pVDZGN3VnczVSUGoKSXgxYXVKSlJBRE94bXFnQUJoU2hveFRZMGJnL0JTekNHaFEwckRNVjBhMU1MMzNGcHZpOXN5T2ZXN0ozM0FTYwpadWdpS1dhWDNJZm5xeDFNV1p6TjVEc3ZHNm5ZQisyUzlLdEdFMU84YjZZT3F3YmM0dmVpdXExa0p5ZmtReS9FCmZFeG9GMnpwWXBiQmJOQTJTRVgxNW1zZEZ3QStTd1p6c0FnL1pLVVdJK2VIQVJySnNKcTRmUXllY3FERWdiL1YKVzZQTUlDZDh2YS93WGZKalZRL3JrVjBPc0MvMzNSUWc4TlFXRGg3eXJGRWUrZE85bTZPaU9UV0xzdFMrdjZjUQphVzY5c3BtN0JseE4wN3IrMXhiL0d5Z0IrNW1Ua1NhMGtuUXY5dFJ5d1FLQmdRRGFPVkpxYjdWMURUUSttWTNNCmt0MklrTDhLLzllQ29XOThOMWg0RVVQQ2pGYk1XVkZNSGJPckpEeTNnSyt2S1g3Vk5GeDVIUXgveTB4S2J6N1MKUmZzZ0F0YnlHaTFObmI2bUVKK2JmNjFvaTdCdy9neCtEajJXUDNvUzRsZnVuZlBrc0RkbTZaKzVlcW1xRk1UQgpRL09SWnFCcXVSLys3ZWkzWDFJbnhSc0o4UUtCZ1FEUzJ5a2oybEZycjNsenFIMTNBSGdEdlVwL1JkeU9YajJKCmp2dWVGQUdYMEhHdXo1N0hPM3YyTTl4dWlPbXUwbzcrZjlTaEc2UjEycitYaU9hRTA0dnRkM3loSEhsVXY3bXUKa211c0FLUDM5U1VtOTdMT0lqaDNickZNRkorS1BkcmxhR2syckppaHZJbmRZcklUbUFVcm9SaEFGTm5BcnhHYQp0Z3R5SVZtMEF3S0JnR1Z0c1RYUmVEalFpMUR4VkN3YXN5Y3ZoK3hYMzlaU3JKdkNxYmNjNXk2OHhmY3pLSXRGClh1WVQ4TGlsOG9KcXVnM2t5WHB0bXdxbTltMithU2VZNlZFR29OdGtlVndURHJMbkZSaFVic2doN1QrSGhVenQKMTRoSE5ya2lSUmFlaWVib1ZNZmJuS2E4TWJIZzkxYVErOXZBSkoyV01CM3dmSE1HdGd2UUhISXhBb0dCQUwvKwo5WkFDN0I2czhsOGhMZFZkSk9ycXd0bnZLQ3l1blVRVFlRUUkzWVo2TS9ua2JZU21vbktGdUpNaHNmOFJGVW1oCjVtQW94bkRXRlowSytEUThXRzZMWFgxcWF3U0RhN1VNK0dQdlZWNmo1d2Q3aG1IeWdRNG5TZU9uNTdtK0p3SzcKTndxazBIcDlMZC9iVGFGUHpHMTB5NXNXSVUwMVhFZE91azliRk00M0FvR0JBTFg5T0gzdkorQy9vc2pHZWtRZgp6VU85c2owcjNFK2xTV3ZHOGg0OVNqL0VkVStpTTZETm5JYVBhdDBzekoxNGdQU2grbktqRHRRbk9NMzRLZzRnCk1YT1hOL1MydTNYeHo5SEo3NHRTZi9PWEtHV2dUNWpxY0JnOHc1a2hyMk5OUTNYZ3M5eWE5UnNGTTFZZFBIM24KeGkvZk9pcnl3K3FKVWkvalgxeHdqdjkwCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K'
  tls.crt: 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVuakNDQTRhZ0F3SUJBZ0lKQUtZQUtNeDB3U1J3TUEwR0NTcUdTSWIzRFFFQkN3VUFNSUdXTVFzd0NRWUQKVlFRR0V3SkNVakVMTUFrR0ExVUVDQXdDVUVVeER6QU5CZ05WQkFjTUJsSmxZMmxtWlRFWU1CWUdBMVVFQ2d3UApUVzlyWVNCVVpXTnViMnh2WjJsaE1Rc3dDUVlEVlFRTERBSklVVEVZTUJZR0ExVUVBd3dQVFc5cllTQlVaV051CmIyeHZaMmxoTVNnd0pnWUpLb1pJaHZjTkFRa0JGaGxrWlhadmNITkFiVzlyWVhSbFkyNXZiRzluYVdFdVkyOXQKTUI0WERUSXlNRE13T1RFM01EY3pNRm9YRFRJek1EY3lNakUzTURjek1Gb3dnWmt4Q3pBSkJnTlZCQVlUQWtKUwpNUXN3Q1FZRFZRUUlEQUpRUlRFUE1BMEdBMVVFQnd3R1VtVmphV1psTVJjd0ZRWURWUVFLREE1TmIydGhWR1ZqCmJtOXNiMmRwWVRFVk1CTUdBMVVFQ3d3TVNHVmhaSEYxWVhKMFpYSnpNUkl3RUFZRFZRUUREQWxzYjJOaGJHaHYKYzNReEtEQW1CZ2txaGtpRzl3MEJDUUVXR1dSbGRtOXdjMEJ0YjJ0aGRHVmpibTlzYjJkcFlTNWpiMjB3Z2dFaQpNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUN6dmRlMmp0UHl6bzJzaW84OENLU3VPczJqCk9jYVY1M2V3NUxrQTlTWSs3YlFqaWN0YlBKZlVSVi82WDFJV2pteEkwYXFybXNkb3VwRkRIWHoxRWsrTzJJaHUKQ0NEVEJ4UG1naFFrZWxwR3RneURxMktCM0VyRFNVaGVzRnBiUnJmQ2dZUGczaUdPSEtZQUE3Q3lUczB3YXZUWQo2ekZzRWVISUhLWHBXRUNGWVRKM1g2cG1qMGd2RG13VHlWeEhBS2ZQNHZNNUdxSHRiMGZLdVlQNSt1ei9EaVhLCnVDY3VWYVJybDhGV1EyN3cyRVhiaVVEVmQ1MkEvV1pwRkZGcldnZTBzOElPKzJsdmdsT2J5OWdqZmF2d2ZvL0wKSkxhNTB5NzFPYVBXeUo2VTU0MmV0TUhBVWhMN2RGNGdLNjNCZGlXZWZuaVR1dm1NeHRicnVBN1lGNUhUQWdNQgpBQUdqZ2Vrd2dlWXdnYlVHQTFVZEl3U0JyVENCcXFHQm5LU0JtVENCbGpFTE1Ba0dBMVVFQmhNQ1FsSXhDekFKCkJnTlZCQWdNQWxCRk1ROHdEUVlEVlFRSERBWlNaV05wWm1VeEdEQVdCZ05WQkFvTUQwMXZhMkVnVkdWamJtOXMKYjJkcFlURUxNQWtHQTFVRUN3d0NTRkV4R0RBV0JnTlZCQU1NRDAxdmEyRWdWR1ZqYm05c2IyZHBZVEVvTUNZRwpDU3FHU0liM0RRRUpBUllaWkdWMmIzQnpRRzF2YTJGMFpXTnViMnh2WjJsaExtTnZiWUlKQUlsNlNaV20wZ1ErCk1Ba0dBMVVkRXdRQ01BQXdDd1lEVlIwUEJBUURBZ1R3TUJRR0ExVWRFUVFOTUF1Q0NXeHZZMkZzYUc5emREQU4KQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBQ1VoeXJ0Wm9lZ3M4MHdpckxuQ2hEUExHQ1UrcUpxNXJZa2hxRStncwoySXJWdjRsMWNZZ1dXYVYvVWRKcVlNTXlqV3FtN2N4bW5weXRZZEVjazhOMlRzNm1jWXE1VVdPZjc4cTMvWHU3Cjc4aWhobkZoMFNNUGxwRXFTaGFNdHhBSlhlT1hncUFNQUpmSEU3ZlQ2OVM0Y1FKK2Fka0hmR1NrMC9ONnI0YngKM0RMdEpiODZlNk5IREVWVnBpS2JPMGJ6YjFOcFZydG1pUVE5YTNUek8rdlNWVEFCY2pOQk0rbzJ4c0Q5TWdnTApGVzgvRFYrMHk5dnhtMlczUjAvYlNPT3llcE9PMTh3RXF0bXphRTVjWWJ2VEc4RjB1c3FZVVBIN3hRLzJjaGMzCjRjT1l0WExpMkhoWFhJUGNhMU9HMWpBaVd4VG9vS1l0TFdaRTRPaDUxWVkwSHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=='
---
apiVersion: v1
kind: Service
metadata:
  name: gzip-uploader
  namespace: dev
  labels:
    app: gzip-uploader
    component: gzip-uploader
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: gzip-uploader
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gzip-uploader
  namespace: dev
spec:
  selector:
    matchLabels:
      app: gzip-uploader
  template:
    metadata:
      labels:
        app: gzip-uploader
        component: gzip-uploader
    spec:
      containers:
        - name: gzip-uploader
          image: ghcr.io/moatorres/gzip-uploader
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              memory: '64M'
              cpu: '10m'
            limits:
              memory: '256M'
              cpu: '100m'
          env:
            - name: PORT
              value: '3000'
            - name: HOST
              value: 'localhost'
            - name: NODE_ENV
              value: 'development'
            - name: UPLOADS_DIR
              value: 'uploads'
            - name: STORAGE_TYPE
              value: 'local'
            - name: TRUST_PROXY
              value: '1'
            - name: NODEMON
              value: 'true'
            - name: TLS_CERT
              valueFrom:
                secretKeyRef:
                  name: gzip-uploader-tls
                  key: tls.key
            - name: TLS_KEY
              valueFrom:
                secretKeyRef:
                  name: gzip-uploader-tls
                  key: tls.crt
